# Generated by Django 5.1.3 on 2024-12-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_profile_fields'),
        ('users', '0002_profile_bio_profile_joined_date_profile_location_and_more'),
    ]

    operations = [
    ]
