# Generated by Django 5.1.4 on 2025-01-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0003_add_ticket_timestamps'),
        ('recognition', '0003_ticket_closed_at_ticket_previous_status_and_more'),
    ]

    operations = [
    ]
